### PR TITLE
Replace platform's Logging source generator

### PR DESCRIPTION
**Pull request by joperezr**
cc: @geeknoid @RussKie @ViktorHofer @tarekgh 

This PR will make sure that when Microsoft.Extensions.Telemetry.Abstractions package gets referenced, the import of the Microsoft.Extensions.Logging.Abstractions package is disabled as the new referenced package's source generator should take precedence.

For additional context, the package Microsoft.Extensions.Logging.Abstractions has a built-in targets file which will check if the property `DisableMicrosoftExtensionsLoggingSourceGenerator` is set to true, and if so, it will disable the automatic reference of the logging generator included in that package. The changes in this PR are just setting that value when the extensions Telemetry package gets referenced, in order to replace the logging generator with the extensions version.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4238)

### CODE REVIEW

**Comment by joperezr** [comment]
@ViktorHofer this currently doesn't work when targeting netcoreapp3.1, because currently the logging.abstractions package has a different buildTransitive .targets file for  that TFM which just shows the not supported warning instead of having the mechanism that the rest of the TFMs have for disabling the source generator:

image

You would need a workaround similar than the one I'm introducing here which allows for extra content on that generated file in order for this to work.

**Review by geeknoid — COMMENTED** [review]
Terrific!

**Review by geeknoid — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> @ViktorHofer this currently doesn't work when targeting netcoreapp3.1, because currently the logging.abstractions package has a different buildTransitive .targets file for that TFM which just shows the not supported warning instead of having the mechanism that the rest of the TFMs have for disabling the source generator

This is by design as packages produced by dotnet/runtime don't support netcoreapp3.1. The runtime has been out-of-support since December 2022. We communicate this via the Warning task that we emit. cc @ericstj

**Comment by xakep139** [comment]
@joperezr does this PR resolves #4207?
If so, could you please link these two?

**Comment by joperezr** [comment]
Yes, it does. 🙂

**Pull request merged**
