### PR TITLE
[ci] Enable source-indexer on internal pipeline for windows

### PR DESCRIPTION
**Pull request by radical**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/5274)

### CODE REVIEW

**Comment by radical** [comment]
Working step on the internal pipeline - https://dev.azure.com/dnceng/internal/_build/results?buildId=2491116&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=316d5c15-0c50-544e-8051-e6b14a1ab674

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
> Working step on the internal pipeline - [dev.azure.com/dnceng/internal/_build/results?buildId=2491116&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=316d5c15-0c50-544e-8051-e6b14a1ab674](https://dev.azure.com/dnceng/internal/_build/results?buildId=2491116&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=316d5c15-0c50-544e-8051-e6b14a1ab674)

Is it worth running full internal CI to verify it won't upset anything?

**Comment by radical** [comment]
> > Working step on the internal pipeline - [dev.azure.com/dnceng/internal/_build/results?buildId=2491116&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=316d5c15-0c50-544e-8051-e6b14a1ab674](https://dev.azure.com/dnceng/internal/_build/results?buildId=2491116&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=316d5c15-0c50-544e-8051-e6b14a1ab674)
> 
> Is it worth running full internal CI to verify it won't upset anything?

No harm in waiting for a full run.

**Comment by radical** [comment]
New run - https://dev.azure.com/dnceng/internal/_build/results?buildId=2491134&view=results .

Feel free to merge this, and the https://github.com/dotnet/source-indexer/pull/160 if the build completes without issues.

**Pull request merged**
