### PR TITLE
Onboard new inter-branch merge flow [Configuration]

### PR DESCRIPTION
**Pull request by f-alizada**
### Context
Onboarding new merge flow based on the github actions

### Changes Made
Added configuration file. The flow was copied from: https://github.com/dotnet/versions/blob/main/Maestro/subscriptions.json. Currently it will not be read or change any behaviour of the merge flow but will be used by the new workflow.

### References
Documentation https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md
One pager: https://github.com/dotnet/dnceng/blob/main/Documentation/OnePagers/github-action-inter-branch-merge.md
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/5239)

### CODE REVIEW

**Comment by f-alizada** [comment]
@joperezr Could you please check this PR and let me know if this is something that you would like to take into the dotnet/extension?

**Comment by RussKie** [comment]
@f-alizada could you help us understand how we could check this PR? Is this ready for review? How do we know it is working? 
Thank you

**Comment by joperezr** [comment]
I am so sorry for the delay in the response here, I've been swamped lately. Thank you for the PR, we want to keep the main to dev subscription, but the release/8.0 one we don't really need it anymore.

**Comment by joperezr** [comment]
> @f-alizada could you help us understand how we could check this PR? Is this ready for review? How do we know it is working? 
> 
> Thank you

@RussKie sorry I have context here, they are deprecating the inter-branch flow PRs from maestro and instead moving to GH Actions, so this is the PR moving the existing subscriptions we have in maestro to that.

**Comment by RussKie** [comment]
Thank you for the explanation.
If you're certain it is working - :shipit:

**Review by mmitche — APPROVED** [review]

**Pull request merged**
