### PR TITLE
Update BenchmarkDotNet

### PR DESCRIPTION
**Pull request by JamesNK**
Mirror https://github.com/dotnet/aspnetcore/pull/19482

### CODE REVIEW

**Comment by JamesNK** [comment]
Talked with @sebastienros and only thing external tools care about is the CSV output which should be unchanged.

**Comment by JunTaoLuo** [comment]
Note that we moved the source to aspnetcore already so this PR should be migrated as well.

**Comment by dougbu** [comment]
@JamesNK did you make the necessary changes in dotnet/aspnetcore? If yes, suggest closing this PR.

**Comment by JamesNK** [comment]
Ya

**Pull request closed without merging**
