### PR TITLE
Nuke DependencyInjection.NamedServices

### PR DESCRIPTION
**Pull request by geeknoid**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4225)

### CODE REVIEW

**Comment by geeknoid** [comment]
Tests will fail in this PR until https://github.com/dotnet/runtime/issues/89447 is fixed.

**Comment by xakep139** [comment]
> Tests will fail in this PR until [dotnet/runtime#89447](https://github.com/dotnet/runtime/issues/89447) is fixed.

It is fixed

**Comment by geeknoid** [comment]
> > Tests will fail in this PR until [dotnet/runtime#89447](https://github.com/dotnet/runtime/issues/89447) is fixed.
> 
> It is fixed

Yeah, I noticed. We need to wait for Arcade to update this repo to point to the latest bits from dotnet/extensions. This should happen in the next few days.

**Comment by RussKie** [comment]
We're blocked by https://github.com/dotnet/aspnetcore/pull/49704.

**Review by joperezr — APPROVED** [review]
LGTM barring a green build once we fix the ingestion flow.

**Pull request merged**
