### PR TITLE
Resolve a "FIXME" in Options.Validation

### PR DESCRIPTION
**Pull request by xakep139**
This PR is a follow-up after https://github.com/dotnet/runtime/pull/84280 was merged

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4111)

### CODE REVIEW

**Comment by xakep139** [comment]
@RussKie FYI

**Comment by geeknoid** [comment]
Why do we need this change? We should be deleting the stuff in ToBeRemoved if possible, rather than patching it...

**Comment by xakep139** [comment]
🤦‍♂️ my bad, haven't noticed the folder name. I was viewing the code via VS in solution view only. Abandoning th PR.

**Comment by RussKie** [comment]
> We should be deleting the stuff in ToBeRemoved if possible,

@geeknoid @joperezr do we have a plan for Options.ValidateOnStart project? It's the only one in the "ToBeRemoved" folder.

**Comment by RussKie** [comment]
I guess this is https://github.com/dotnet/runtime/issues/84347 and https://github.com/dotnet/runtime/issues/86511?

**Pull request closed without merging**
