### PR TITLE
IExternalScopeProvider can now be injected (#2409)

### PR DESCRIPTION
**Pull request by TheXenocide**
- Added IExternalScopeProvider parameter to LoggerFactory to allow injection.
- Registers default implementation if not otherwise registered.

Addresses #2409

Note: this is currently based on the release/3.0 branch since I verified that it would solve the problems I'm having with the current stable release. I can rebase to 3.1 if necessary.

### CODE REVIEW

**Comment by davidfowl** [comment]
> Note: this is currently based on the release/3.0 branch since I verified that it would solve the problems I'm having with the current stable release. I can rebase to 3.1 if necessary.

Best to assume that everything goes into master. There's an approval process for things to make it into 3.1 and this doesn't meet the bar.

**Comment by TheXenocide** [comment]
Just so I understand what you mean about 3.1, is that meaning our team definitely won't be able to use IExternalScopeProvider until .NET 5.0? I don't mind rebasing to master, just wondering what the implications are for our adoption schedule and what kinds of requests *do* meet the bar for 3.1 (I'm guessing this just means the scope of work is already finalized)? Other than that, one thing this PR does is mark a method as virtual, though I'm wondering if that's not worth discussing further (possibly in the original feature request; not really sure where would be more appropriate)? Thanks for your time.

**Comment by davidfowl** [comment]
> Just so I understand what you mean about 3.1, is that meaning our team definitely won't be able to use IExternalScopeProvider until .NET 5.0? I don't mind rebasing to master, just wondering what the implications are for our adoption schedule and what kinds of requests do meet the bar for 3.1 (I'm guessing this just means the scope of work is already finalized)? Other than that, one thing this PR does is mark a method as virtual, though I'm wondering if that's not worth discussing further (possibly in the original feature request; not really sure where would be more appropriate)? Thanks for your time.

Yes that's correct. The 3.1 bar is *extremely high*, you can think about it like a patch for 3.0 (mostly bug fixes and critical feedback from 3.0). This is a new feature that introduces a new API which needs to be reviewed and signed off and doesn't meet that bar.

**Comment by TheXenocide** [comment]
global.json in master is set to .NET 5 Alpha already, which I haven't found anywhere (and I'm not particularly excited about building all of .NET from source just to modify a few lines here and there). Is there guidance for how to work against master?

**Comment by TheXenocide** [comment]
Okay, found the installer for latest SDK bits

**Comment by TheXenocide** [comment]
I haven't forgotten about this, but now that we've worked around the issue at the office, any contribution I make will likely be from home (harder to find spare time, but probably better for keeping my build environments isolated since I really don't want to install the preview SDK on my work machine).

**Pull request closed without merging**
