### PR TITLE
Update to Polly 8.0.0

### PR DESCRIPTION
**Pull request by martincostello**
Update to the stable release of Polly v8.

/cc @geeknoid @martintmk

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4483)

### CODE REVIEW

**Comment by geeknoid** [comment]
@joperezr Remind me of the voodoo needed to pull in a new dependency? We now want to reference the new Polly.Core

**Comment by sebastienros** [comment]
@geeknoid I think you mean this pipeline https://dev.azure.com/dnceng/internal/_build?definitionId=931

Click on Run Pipeline and fill-up the form, ping me if you have questions.

**Comment by geeknoid** [comment]
@sebastienros Oh yeah, I remember now that I don't have access to this pipeline for some reason. Could you run it please? We need to pull in Polly.Core V8.

Thanks.

**Comment by sebastienros** [comment]
It's published now

**Comment by martincostello** [comment]
Looks like not all of the three required packages have been imported to your package feed.

**Comment by martintmk** [comment]
> Looks like not all of the three required packages have been imported to your package feed.

Should be fine now, however, there are some build errors related to some minor API changes.

**Comment by martincostello** [comment]
@martintmk You might have to finish this one off for me, because I can't actually build the solution locally myself due to #4483

**Comment by martintmk** [comment]
> @martintmk You might have to finish this one off for me, because I can't actually build the solution locally myself due to #4483 and there's failing tests.

Can you change the 'PrimaryContext' to 'ActionContext'? If that does not help I'll try.

**Comment by martincostello** [comment]
Looks like the same failures with the different context.

**Comment by martintmk** [comment]
Closing in favor of #4489

**Pull request closed without merging**
