### PR TITLE
Update links for repository move/rename

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
@dotnet/aspnet-build - looks like `extensions-ci` isn't running, and the case sensitive `Extensions-ci` is blocking.  Any ideas?  @dougbu ?

**Comment by dougbu** [comment]
I can't fix the branch protection rules 'til the pipeline runs and GitHub notices. Trying&hellip;

**Comment by dougbu** [comment]
Was anything different done w/ the extensions-ci pipeline than (say) aspnetcore-ci or blazor-ci? I can't see anything obvious.

**Comment by Pilchie** [comment]
Not that I know of.  Maybe I manually queued a ci run on the AzDO site when I did the renames?  Looks like there was a passing CI run yesterday that was manually triggered.

**Comment by Pilchie** [comment]
So, what are next steps here?  @mmitche any ideas why this check wouldn't get updated?

**Comment by mmitche** [comment]
pipeline had the wrong service connection (should have been dotnet not aspnet)

**Comment by Pilchie** [comment]
Are the other repos okay?  I thought they were still using the aspnet connection too?

**Pull request merged**
