### PR TITLE
Restrict keywords and log levels enabled in EventCountersListener

### LINKED ISSUE #4104: EventCountersListener enables all keywords and all log levels on enabled event sources
This leads to high CPU usage which leads to performance problems. 
I'm pretty sure it's this line of code coming from the event counter to meter translation layer:

https://github.com/dotnet/extensions/blob/996fcd8344ac8f4601e464884e869bc0821a1cc2/src/Libraries/Microsoft.Extensions.Telemetry/Metering.Collectors.EventCounters/EventCountersListener.cs#L234

It's turning on all of the keywords and all of the event verbosity.
 
For reference, here's the otel version:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/0de8b8a2755b1c5079d369aa63203184703c00c8/src/OpenTelemetry.Instrumentation.EventCounters/EventCountersMetrics.cs#LL197C37-L197C37

We should make these match.

### PR DESCRIPTION
**Pull request by xakep139**
This PR fixes #4104

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4109)

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

**Review by geeknoid — APPROVED** [review]

**Comment by xakep139** [comment]
Test failures seem unrelated - `MetricCollectorTests.Dispose` and `Diagnostics.ResourceMonitoring.Linux`

**Comment by joperezr** [comment]
Test failure is:
```
  Failed Microsoft.Extensions.Telemetry.Testing.Metering.Test.MetricCollectorTests.Dispose [9 ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.Extensions.Telemetry.Testing.Metering.Test.MetricCollectorTests.Dispose() in /_/test/Libraries/Microsoft.Extensions.Telemetry.Testing.Tests/Metering/MetricCollectorTests.cs:line 369
--- End of stack trace from previous location ---
```

Is that a known flaky test @RussKie ?

**Comment by xakep139** [comment]
> Test failure is:
> 
> ```
>   Failed Microsoft.Extensions.Telemetry.Testing.Metering.Test.MetricCollectorTests.Dispose [9 ms]
>   Error Message:
>    Assert.True() Failure
> Expected: True
> Actual:   False
>   Stack Trace:
>      at Microsoft.Extensions.Telemetry.Testing.Metering.Test.MetricCollectorTests.Dispose() in /_/test/Libraries/Microsoft.Extensions.Telemetry.Testing.Tests/Metering/MetricCollectorTests.cs:line 369
> --- End of stack trace from previous location ---
> ```
> 
> Is that a known flaky test @RussKie ?

It seems that @geeknoid addressed this in #4113

**Comment by geeknoid** [comment]
The test failure in MetricCollectorTests is brand new, I checked in a workaround for that.

**Pull request merged**
