### PR TITLE
Cleanup unused properties

### LINKED ISSUE #4099: Restore downgraded code coverage
A number of projects have seen their code coverage metrics artificially downgraded while establishing the quality gates. To facilitate that, a custom attribute has been added which ultimately needs to be removed.
For example:
https://github.com/dotnet/extensions/blob/996fcd8344ac8f4601e464884e869bc0821a1cc2/eng/scripts/ValidateProjectCoverage.ps1#L44
https://github.com/dotnet/extensions/blob/052e6c8ca60dd6aad445f06db5f6d1a2f95e7f9f/src/Libraries/Microsoft.Extensions.Diagnostics.Probes/Microsoft.Extensions.Diagnostics.Probes.csproj#L17

Here's the list of affected projects that need to be addressed:
https://github.com/search?q=repo%3Adotnet%2Fextensions%20TempMinCodeCoverage&type=code

### PR DESCRIPTION
**Pull request by geeknoid**
Fix #4099 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4271)

### CODE REVIEW

**Comment by RussKie** [comment]
MC

**Comment by RussKie** [comment]
image

**Comment by RussKie** [comment]
The internal builds have been failing due to the CC, e.g. [this](https://dev.azure.com/dnceng/internal/_build/results?buildId=2241326&view=logs&j=8cf0092d-1f6c-522b-3c27-9f632d33f4f3&t=72ff1a15-e2cd-5f81-8adb-7872a3211815).
image

**Comment by geeknoid** [comment]
I'm forcing this in, since the build is otherwise broken.

**Pull request merged**
