### PR TITLE
Update System.Data.SqlClient to 4.8.6

### PR DESCRIPTION
**Pull request by javiercn**
Updates System.Data.SqlClient to 4.8.6
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/5212)

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by JamesNK** [comment]
I think the build is broken on the release/2.1 branch.

**Comment by wtgodbe** [comment]
> I think the build is broken on the release/2.1 branch.

Fallout from 1es conversion, I think I just fixed it

**Comment by wtgodbe** [comment]
Old blob feed is 403-ing, checking w/ dnceng now

**Pull request merged**
