### PR TITLE
Update branding to 6.0.0-preview3

### PR DESCRIPTION
**Pull request by JunTaoLuo**

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
FYI @Anipik I ended up making this change out of habit.

**Review by dougbu — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
FYI @Anipik can you also tag the preview1 release and delete the preview1 branch when you merge this PR?

**Comment by dougbu** [comment]
> tag the preview1 release

That's odd. I thought tags were created automatically except after 2.1 releases. @leecow❔

**Comment by dougbu** [comment]
@Anipik I don't see a reason _not_ to merge this PR but left the honours to you.

**Comment by JunTaoLuo** [comment]
Though we can merge this PR, I just realized that there are no longer a need to make these types of changes in Extensions after https://github.com/dotnet/extensions/pull/3818

**Comment by Anipik** [comment]
> FYI @Anipik can you also tag the preview1 release and delete the preview1 branch when you merge this PR?

We are working on publishing those packages.

**Pull request merged**
