### PR TITLE
Update HybridCacheOptions.cs (small typo)

### PR DESCRIPTION
**Pull request by jodydonetti**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/5756)

### CODE REVIEW

**Comment by jodydonetti** [comment]
Add missing [reference](https://simple.wikipedia.org/wiki/Mebibyte).

**Comment by mgravell** [comment]
Code change is fine, but we should target `main` ?

**Comment by mgravell** [comment]
Almost certainly `main` - you may be able to simply edit the PR to retarget as long as that doesn't try to bring over all the intermediate commits - or it may be easier to redo the change!  I need to check with @joperezr on what the process is meant to be for the other branches.

**Comment by jodydonetti** [comment]
Done, [here](https://github.com/dotnet/extensions/pull/5757)'s the new one.

**Pull request closed without merging**
