### PR TITLE
Cc enforce

### PR DESCRIPTION
**Pull request by RussKie**
Code coverage enforcement

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4051)

### CODE REVIEW

**Comment by joperezr** [comment]
Seems like this one is replacing #4046? Any reason why not just add the additional commits there?

**Comment by RussKie** [comment]
No, it's based on top of #4046

**Comment by joperezr** [comment]
> No, it's based on top of #4046

My question still stands, why not just add the additional commits there? Seems like the goal of both is enabling code coverage anyway.

**Comment by RussKie** [comment]
Because it's (relatively) simple to enable code coverage collection, and enforcement of the CC is much more involved - e.g., quite a few projects will have to be overridden. 
Also, it's much easier to review, iterate and merge a small targeted pull-request than a pull-request that is large and attempts to do multiple things.

**Comment by RussKie** [comment]
This is ready to merge

**Review by geeknoid — APPROVED** [review]

**Comment by RussKie** [comment]
I had to downgrade Microsoft.Extensions.Telemetry to 78 as the [internal CI failed](https://dev.azure.com/dnceng/internal/_build/results?buildId=2206742&view=logs&j=f08acfff-97c9-54c7-e44f-0ed78f271593&t=0d92665e-47a4-54f9-aeed-b90d65e6ca52).

**Pull request merged**
