### PR TITLE
Add Microsoft.Extensions.Logging.AzureEventHub

### PR DESCRIPTION
**Pull request by jamesharling**
Summary of the changes
 - Adds new logger provider for Azure Event Hubs

Addresses #1771

### CODE REVIEW

**Comment by jamesharling** [comment]
It would be great to get an understanding of the required test coverage for this provider.

**Comment by dougbu** [comment]
@jamesharling please run `dotnet msbuild /t:GenerateReferenceSource` in your new project directory

**Comment by dougbu** [comment]
@anurse @davidfowl does logging have a codeowner these days?

**Comment by anurse** [comment]
Adding a new logger to the built-in set of loggers isn't done lightly. We should have discussion on the original issue as to the impact and maintenance burden here before we go through the code itself.

**Comment by ericstj** [comment]
Closing this for now, please carry on discussion in https://github.com/Azure/azure-sdk-for-net/issues/12033

**Pull request closed without merging**
