### PR TITLE
Update branding to 3.1.13

### PR DESCRIPTION
**Pull request by wtgodbe**
Also update SDK and baseline

### CODE REVIEW

**Comment by wtgodbe** [comment]
@mmitche looks like the new feed is missing `Autofac.Extensions.DependencyInjection` version 4.3.1: https://github.com/dotnet/extensions/blob/ee55630416c35424829a9f06c35a6d4c2d8f481f/eng/Dependencies.props#L78-L85

Not sure if any of the ones below that will be missing as well

**Comment by wtgodbe** [comment]
Many packages still missing here:

> D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package LightInject. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package LightInject. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport
D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package DryIoc.dll. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package DryIoc.dll. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport
D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package Grace. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package Grace. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport
D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package Stashbox. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package Stashbox. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport
D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package StructureMap. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package StructureMap. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport
D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package Unity.Abstractions. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package Unity.Abstractions. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport
D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package Unity.Container. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package Unity.Container. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport
D:\a\1\s\src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj : error NU1101: Unable to find package Lamar. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport [D:\a\1\s\.dotnet\sdk\3.1.112\NuGet.targets]
##[error]src\DependencyInjection\DI.External.Tests\test\Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.csproj(0,0): error NU1101: Unable to find package Lamar. No packages exist with this id in source(s): dotnet-core, dotnet-eng, dotnet-public, dotnet3.1, dotnet3.1-transport

**Review by JunTaoLuo — APPROVED** [review]

**Pull request merged**
