### PR TITLE
Prepare for strict coherency

### PR DESCRIPTION
**Pull request by mmitche**
Strict coherency means that if your repo declares a dependency with a CPD attribute, the CPD parent must have a direct dependency on that dependency.
This means for extensions that it should remove the CPD attributes altogether because they do not do anything and of course runtime can't have a dependency on binaries produced in the same build.

Reasons for this approach over the current approach:
- This eliminates some ambiguous tie-breaking scenarios that are very problematic and dangerous in servicing
- Those tie breaking scenarios require the use of BAR to break the ties. If the DB data were to be lost then the tie-breaking would do unexpected things.

### CODE REVIEW

**Comment by mmitche** [comment]
@dougbu PTAL

**Comment by dougbu** [comment]
> @dougbu PTAL

I'm not involved in work in this repo outside release/2.1 and release/3.1. @ericstj @maryamariyan and @Anipik are on point for 5.0.

**Comment by mmitche** [comment]
> > @dougbu PTAL
> 
> I'm not involved in work in this repo outside release/2.1 and release/3.1. @ericstj @maryamariyan and @Anipik are on point for 5.0.

Hah..it keeps listing you as a code owner.

**Comment by dougbu** [comment]
> > > @dougbu PTAL
> > 
> > I'm not involved in work in this repo outside release/2.1 and release/3.1. @ericstj @maryamariyan and @Anipik are on point for 5.0.

> Hah..it keeps listing you as a code owner.

@Anipik I could remove myself and others from .github/CODEOWNERS but it's probably better if you and others update that file to match current ownership.

**Pull request merged**
