### PR TITLE
Don't publish Microsoft.AspNetCore.Testing

### PR DESCRIPTION
**Pull request by RussKie**
Addresses https://github.com/dotnet/dnceng/issues/174
Relates to https://github.com/dotnet/extensions/issues/4057

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4058)

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
I think renaming this would still be valuable, can you open a tracking issue?

**Comment by RussKie** [comment]
> I think renaming this would still be valuable, can you open a tracking issue?

https://github.com/dotnet/extensions/issues/4057 ;)

**Comment by wtgodbe** [comment]
Whoops, my bad 😆

**Pull request merged**
