### PR TITLE
Replaced eval script with native command to read from redis. Native commands have better performance compared to EVAL/EVALSHA scripts

### PR DESCRIPTION
**Pull request by BrennanConroy**
Forward port of https://github.com/dotnet/extensions/pull/3643 to 5.0

cc @Pilchie

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Just realized, this probably isn't needed since we're merging the 3.1 one and it'll merge forward to 5.0

**Comment by BrennanConroy** [comment]
I assume this can be merged now?

**Comment by BrennanConroy** [comment]
cc @Anipik

**Comment by Anipik** [comment]
> I assume this can be merged now?

yes this can be merged.

**Pull request merged**
