### PR TITLE
Escape C# strings using helper

### PR DESCRIPTION
**Pull request by sebastienros**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4407)

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by xakep139** [comment]
@dbarbosapn FYI

**Comment by xakep139** [comment]
@sebastienros thank you for the fix! Do you think we need to extend the same approach to other source-gens?

**Comment by geeknoid** [comment]
Oh, I didn't know this existed. I have a custom version of the conversion function in the logging generator, I'll check in the others.

@tarekgh The existing options validator generator has an EscapeString function that should be replaced by the Roslyn function.

**Review by geeknoid — APPROVED** [review]

**Comment by tarekgh** [comment]
> The existing options validator generator has an EscapeString function that should be replaced by the Roslyn function.

I can track this for .NET 9.0.

**Comment by sebastienros** [comment]
@xakep139 I think so, I only changed this component as I was reviewing it and wanted to keep my focus.

**Pull request merged**
