### PR TITLE
Add tsaconfig

### PR DESCRIPTION
**Pull request by danmoseley**
* Copy https://github.com/dotnet/aspire/pull/4860
* Move existing empty credscan suppressions file to the location used by other repos to be consistent. (Was it being picked up before, without a tsa config file?)

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/5285)

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
LGTM, thanks for getting this done @danmoseley!

Regarding the rename of CredScanSuppressions, I'm assuming this is following 1ES guidelines of where they should be located at?

**Comment by mmitche** [comment]
Can you enable policheck in the 1ES templates with this PR?

**Comment by danmoseley** [comment]
Added. Jose after this goes in you'll want to check that all the right tools and things run..

**Comment by joperezr** [comment]
> Added. Jose after this goes in you'll want to check that all the right tools and things run..

Yeah, one thing we can do is before merging, we can trigger an internal build from your branch and then do a diff to make sure all the right steps are still running.

**Comment by danmoseley** [comment]
I'll let you do that since you are probably a better person to interpret it..

**Pull request merged**
