### PR TITLE
Allowing tags to start with _

### PR DESCRIPTION
**Pull request by carolineRe13**
Making it possible for tags to start with _

We want to use OT exporter with code gen. However, to override namespaces, we need to pass a tag which starts with "_"
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/5478)

### CODE REVIEW

**Comment by RussKie** [comment]
Could you please add tests for this change too?

**Comment by carolineRe13** [comment]
@dotnet-policy-service agree [company="Microsoft"]

**Comment by carolineRe13** [comment]
@dotnet-policy-service agree company="Microsoft"

**Comment by evgenyfedorov2** [comment]
As per the OpenTelemetry naming conventions https://opentelemetry.io/docs/specs/semconv/general/attribute-naming/#recommendations-for-opentelemetry-authors names must not start with an underscore. Will check if it applies here

**Review by evgenyfedorov2 — APPROVED** [review]

**Comment by evgenyfedorov2** [comment]
@carolineRe13 did you close it without merging?

**Comment by carolineRe13** [comment]
@evgenyfedorov2 was by accident, will merge it now as soon as the build reran

**Comment by RussKie** [comment]
This was discussed internally with the Geneva team; this change poses no issues.

**Pull request merged**
