### PR TITLE
Add support for repeated XML elements without a Name attribute in configuration XML files.

### PR DESCRIPTION
**Pull request by amoerie**
I'm recreating my original PR here, as requested in https://github.com/aspnet/Configuration/pull/816#issuecomment-447602727 by @ajcvickers 

I know this is a considerable change in the existing code, but all existing tests are still intact and green. The "Name" feature is still completely supported and as such, this is not a breaking change.

Addresses #485
Addresses #761

### CODE REVIEW

**Comment by amoerie** [comment]
@ajcvickers Is there anything holding back this PR? Other than busy schedules. 😉

**Comment by ajcvickers** [comment]
@amoerie Nope. Just time.

**Comment by amoerie** [comment]
Fair enough, thanks!

**Comment by hacst** [comment]
Looking forward to this landing. Not being able to express lists like I was used to from json configs when the app uses xml instead was quite unexpected.

Is there a rough timeframe for this landing by now?

**Comment by Jan-Magerl** [comment]
With this solution you are still not able to use IOption 

```
public class Config
{
  public List<Item> Items { get; set};
}
services.Configure<Config>("Section")
```

will not fill the list.

This is because of the ItemName don't exists in Jsonfiles. 

```
{
  "Section":"{
    "Items": [
      {
         "Name": "item1"
      },
      {
         "Name": "item2"
      }
}
```

JsonConfigurationProvider would build paths like
Section:Items:0:Name
Section:Items:1:Name

XmlConfigurationprovider build the path

```
<configuration>
  <section>
    <Items>
      <Item>
        <Name>Item1</Item>
      </Item>
      <Item>
        <Name>Item2</Item>
      </Item>
    </Items
  </section>
</configuration>
```

Will generate 
Section:Items:**_Item_**:0:Name
Section:Items:**_Item_**:1:Name

But IOptions don't want the Item part

Is there any possibility to remove "Item"?

**Comment by amoerie** [comment]
If you don't want "Item" to appear in the config list, I believe you can do the following: (with the changes from this PR)

```
<configuration>
  <section>
    <Items><Name>Item1</Name></Items>
    <Items><Name>Item2</Name></Items>
  </section>
</configuration>
```

**Comment by Jan-Magerl** [comment]
> @Jan-Magerl
> 
> If you don't want "Item" to appear in the config list, I believe you can do the following: (with the changes from this PR)

I also want to use XmlSerializer to write to the File, without weird Attributes.
I have found a Solution that works for me:

Change Line 224:
```
    public string GetKey()
    {
      var tokens = new List<string>(3);
      // root element does not contribute to prefix
      if (Parent != null && !Multiple) tokens.Add(ElementName);
      ...
```

This will fix my Issue, but maybe the behavior of IOptions should be fixed.

**Comment by jez9999** [comment]
I really wish this would get merged.  I could do with some array-like behaviour in my XML configuration.

**Comment by amoerie** [comment]
> As per [aspnet/Announcements#411](https://github.com/aspnet/Announcements/issues/411), we are currently migrating components from this repository to other repositories. This PR targets components that have been moved to [dotnet/runtime, in the src/libraries directory](https://github.com/dotnet/runtime/tree/master/src/libraries). If you're still interested in contributing this change, please retarget your PR to dotnet/runtime and reference the original issue discussing the change or bug fix. If you have questions, or need guidance on how to port your change, please tag `@dotnet/extensions-migration` in a comment and we'll try to help.

I've already migrated this pull request once. This pull request has been left open for more than a year. Obviously, there is no interest to actually merge this, so I don't think I'll spend the time again.

**Comment by jez9999** [comment]
@amoerie That's a shame.  There's an issue with Serilog config where it requires sinks to be in an array and a property in each array object is actually called...... "Name".  So it clashes with the XML "name" attribute requirement.  Could really do with a fix.

**Comment by DanielSundberg** [comment]
I would also like to see this merged. I stumbled into this issue while trying to add some legacy config files to a new dotnet core project.

**Comment by amoerie** [comment]
> @amoerie That's a shame. There's an issue with Serilog config where it requires sinks to be in an array and a property in each array object is actually called...... "Name". So it clashes with the XML "name" attribute requirement. Could really do with a fix.

It's not that I'm unwilling to do the work again, it's that I'm not convinced this PR would get any attention, exactly as before. If I can get an "official" confirmation that this PR would be strongly considered for merging, I am willing to make it happen again.

**Comment by maryamariyan** [comment]
> It's not that I'm unwilling to do the work again, it's that I'm not convinced this PR would get any attention, exactly as before. If I can get an "official" confirmation that this PR would be strongly considered for merging, I am willing to make it happen again.

@amoerie I see that your PR was blocked two twice because two different repo consolidations. The source code is now moved to dotnet/runtime. Are you still interested in pushing a PR for this?

**Comment by amoerie** [comment]
Hi @maryamariyan I made the pull request here: https://github.com/dotnet/runtime/pull/43722 

I'm glad to see this is being followed up on.

**Pull request closed without merging**
